backend = "glx";
vsync = false;
detect-client-opacity = false;
unredir-if-possible = false;

blur: {
    method = "gaussian";
    size = 5;
    deviation = 3.0;
    strength = 5.0;
};

corner-radius = 12;

shadow = false;

rules = (
    {
        match = "class_g = 'slop' || class_g = 'i3lock' || class_g = 'Rofi' || class_g = 'Dunst' || class_g = 'Polybar' || name = 'Notification'";
        corner-radius = 0;
        shadow = false;
    },

    {
        match = "class_g = 'Yad'";
        opacity = 0.90;
    },

    {
        match = "class_g = 'Dunst'";
        opacity = 0.90;
    },
    {
        match = "class_g = 'Polybar'";
        opacity = 0.90;
        corner-radius = 0;
    },

    {
        match = "class_g = 'Rofi'";
        opacity = 0.90;
        corner-radius = 0;
    },

# Still waiting fix of broken animations...
#    {
#        match = "class_g = 'Alacritty' && focused";
#        opacity = 0.90;
#    },

#    {
#        match = "class_g = 'Alacritty' && !focused";
#        opacity = 0.70;
#    },

    {
        match = "class_g = 'Alacritty' || class_g = 'alacritty_floating'";
        opacity = 0.90;
    },

    {
        match = "fullscreen";
        opacity = 1.0;
        corner-radius = 0;
    }
);

animations = (
    {
        triggers = [ "open" ];
        preset = "appear";
        duration = 0.20;
        scale = 0.96;
    },

    {
        triggers = [ "close" ];
        preset = "disappear";
        duration = 0.18;
        scale = 0.96;
    },

    {
        triggers = [ "geometry" ];
        preset = "geometry-change";
		duration = 0.25;
        curve = "cubic-bezier(0.22, 1, 0.36, 1)";
    }
);