[mgr]
show_hidden = true
show_symlink = true
tab_size = 4

[opener]
edit = [
    { run = 'nano %s', block = true, for = "unix" },
]

[plugin]
prepend_previewers = [
    { mime = "*executable*", run = "exiftool" },    
]
prepend_fetchers = [
    { url = "*", run = "git", group = "git" },
    { url = "*/", run = "git", group = "git" },
]
