# System Variables

# `ls -1 /sys/class/power_supply/`
# `ls -1 /sys/class/backlight/
# `ip link | awk '/state UP/ {print $2}' | tr -d :` 

[system]
adapter = ACAD
battery = BAT0
graphics_card = amdgpu_bl1
network_interface_wireless = wlp1s0
network_interface_wired = enp9s0
